apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-api-v2
  namespace: dev
  uid: 7dcdb612-e076-4d9e-a5e8-dd1ca16d7277
  resourceVersion: '4732959'
  generation: 3
  creationTimestamp: '2021-08-02T19:48:24Z'
  labels:
    app: model-api-v2
    language: all
  annotations:
    deployment.kubernetes.io/revision: '3'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2"},"creationTimestamp":"2021-08-02T19:48:24Z","generation":2,"labels":{"app":"model-api-v2","language":"all"},"managedFields":[{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{".":{},"f:app":{},"f:language":{}}},"f:spec":{"f:progressDeadlineSeconds":{},"f:replicas":{},"f:revisionHistoryLimit":{},"f:selector":{},"f:strategy":{"f:rollingUpdate":{".":{},"f:maxSurge":{},"f:maxUnavailable":{}},"f:type":{}},"f:template":{"f:metadata":{"f:labels":{".":{},"f:app":{},"f:language":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"speech-recognition-model-api\"}":{".":{},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":50051,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:protocol":{}}},"f:resources":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{},"f:volumeMounts":{".":{},"k:{\"mountPath\":\"/opt/speech_recognition_open_api\"}":{".":{},"f:mountPath":{},"f:name":{}}}}},"f:dnsPolicy":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{},"f:volumes":{".":{},"k:{\"name\":\"modelsv2\"}":{".":{},"f:gcePersistentDisk":{".":{},"f:fsType":{},"f:pdName":{},"f:readOnly":{}},"f:name":{}}}}}}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2021-08-11T13:02:07Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:deployment.kubernetes.io/revision":{}}},"f:status":{"f:availableReplicas":{},"f:conditions":{"k:{\"type\":\"Progressing\"}":{"f:lastUpdateTime":{},"f:message":{},"f:reason":{}}},"f:observedGeneration":{},"f:readyReplicas":{},"f:replicas":{},"f:updatedReplicas":{}}},"manager":"kube-controller-manager","operation":"Update","time":"2021-08-11T13:02:19Z"}],"name":"model-api-v2","namespace":"dev","selfLink":"/apis/apps/v1/namespaces/dev/deployments/model-api-v2","uid":"7dcdb612-e076-4d9e-a5e8-dd1ca16d7277"},"spec":{"progressDeadlineSeconds":600,"replicas":15,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"model-api-v2","language":"all"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"model-api-v2","language":"all"}},"spec":{"containers":[{"image":"us.gcr.io/ekstepspeechrecognition/speech_recognition_model_api:2.0.0","imagePullPolicy":"IfNotPresent","name":"speech-recognition-model-api","ports":[{"containerPort":50051,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/opt/speech_recognition_open_api","name":"modelsv2"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"gcePersistentDisk":{"fsType":"ext4","pdName":"modelsv2","readOnly":true},"name":"modelsv2"}]}}}}
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: apps/v1
      time: '2021-08-11T13:02:07Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:language': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
                'f:language': {}
            'f:spec':
              'f:containers':
                'k:{"name":"speech-recognition-model-api"}':
                  .: {}
                  'f:image': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":50051,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/opt/speech_recognition_open_api"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
              'f:volumes':
                .: {}
                'k:{"name":"modelsv2"}':
                  .: {}
                  'f:gcePersistentDisk':
                    .: {}
                    'f:fsType': {}
                    'f:pdName': {}
                    'f:readOnly': {}
                  'f:name': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2021-08-11T17:29:04Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            'k:{"type":"Progressing"}':
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:unavailableReplicas': {}
          'f:updatedReplicas': {}
  selfLink: /apis/apps/v1/namespaces/dev/deployments/model-api-v2
status:
  observedGeneration: 3
  replicas: 19
  updatedReplicas: 7
  readyReplicas: 12
  availableReplicas: 12
  unavailableReplicas: 7
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2021-08-02T19:53:21Z'
      lastTransitionTime: '2021-08-02T19:53:21Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2021-08-11T17:29:04Z'
      lastTransitionTime: '2021-08-02T19:48:24Z'
      reason: ReplicaSetUpdated
      message: ReplicaSet "model-api-v2-578bfb5bf8" is progressing.
spec:
  replicas: 15
  selector:
    matchLabels:
      app: model-api-v2
      language: all
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: model-api-v2
        language: all
    spec:
      volumes:
        - name: modelsv2
          gcePersistentDisk:
            pdName: modelsv2
            fsType: ext4
            readOnly: true
      containers:
        - name: speech-recognition-model-api
          image: 'gcr.io/ekstepspeechrecognition/speech_recognition_model_api:2.0.0'
          env: 
          - name: languages
            value: '["mai","sa"]'
          ports:
            - containerPort: 50051
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: modelsv2
              mountPath: /opt/speech_recognition_open_api/deployed_models/
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

